# Generated by Django 5.1.2 on 2024-10-19 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='updated',
        ),
    ]
